// File generated by manual extraction from google-services.json
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_on_widgets
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxI65C4A2xWTry7zZvrBf791PBxV79CFw',
    appId: '1:37633754213:android:a77b106e2eacce6342328c',
    messagingSenderId: '37633754213',
    projectId: 'cook-and-snap',
    storageBucket: 'cook-and-snap.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxI65C4A2xWTry7zZvrBf791PBxV79CFw', // Reusing Android key as fallback if iOS specific not found
    appId: '1:37633754213:ios:a77b106e2eacce6342328c', // Placeholder, update via FlutterFire CLI if needed
    messagingSenderId: '37633754213',
    projectId: 'cook-and-snap',
    storageBucket: 'cook-and-snap.firebasestorage.app',
    iosBundleId: 'com.example.snap_and_cook_app',
  );
}
